//
// Created by Dawid Drozd aka Gelldur on 16.03.16.
//

#ifndef ESPORTLIVESCORE_EXCAPTIONHELPER_H
#define ESPORTLIVESCORE_EXCAPTIONHELPER_H

#define ERROR_PARAMS

#endif //ESPORTLIVESCORE_EXCAPTIONHELPER_H
